name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make HTML
      run: |
        cd "sphinx"
        #working-directory: sphinx
        #ls
        #pwd
        make html
        cp -r build/html/* ../docs
