name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - name: Make HTML
	  run: make html
	    cp -r sphinx/build/* docs
	  with:
	    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	    BRANCH: master
            FOLDER: docs

