name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
defaults:
  run:
    working-directory: sphinx
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Make HTML
      run: |
        #cd "sphinx"
        ls
        pwd
        #make html
        #cp -r build/html/* ../docs
