name: "Publish sphinx"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setting up python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'
    - name: installing sphinx
      run: pip install sphinx
    - name: checking sphinx version
      run: sphinx-build --version
    - name: checking pwd
      run: pwd
    - name: Changing directory
      run: |
        cd "sphinx"
        ls
        pwd
        make html
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@3.5.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        BRANCH: gh-pages
        FOLDER: sphinx/build/html
